sudo: false
language: node_js
dist: bionic
compiler:
  - clang
  - gcc
node_js:
  - "12"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
matrix:
  include:
    - node_js: "10"
    - node_js: "11"
    - node_js: "12"
    - node_js: "13"
